FROM lcr.loongnix.cn/library/debian:forky

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      git \
      wget && \
    rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
